/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as EngineIndexRouteImport } from './routes/engine/index'
import { Route as FuelIndexRouteImport } from './routes/fuel/index'
import { Route as ModlabIndexRouteImport } from './routes/modlab/index'
import { Route as PerformanceIndexRouteImport } from './routes/performance/index'
import { Route as QualityIndexRouteImport } from './routes/quality/index'
import { Route as ThermalsIndexRouteImport } from './routes/thermals/index'
import { Route as TripsIndexRouteImport } from './routes/trips/index'
import { Route as TripsTripIdRouteImport } from './routes/trips/$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineIndexRoute = EngineIndexRouteImport.update({
  id: '/engine/',
  path: '/engine/',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelIndexRoute = FuelIndexRouteImport.update({
  id: '/fuel/',
  path: '/fuel/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModlabIndexRoute = ModlabIndexRouteImport.update({
  id: '/modlab/',
  path: '/modlab/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceIndexRoute = PerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIndexRoute = QualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThermalsIndexRoute = ThermalsIndexRouteImport.update({
  id: '/thermals/',
  path: '/thermals/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/trips/$tripId',
  path: '/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/engine/': typeof EngineIndexRoute
  '/fuel/': typeof FuelIndexRoute
  '/modlab/': typeof ModlabIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/thermals/': typeof ThermalsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/driver': typeof DriverIndexRoute
  '/engine': typeof EngineIndexRoute
  '/fuel': typeof FuelIndexRoute
  '/modlab': typeof ModlabIndexRoute
  '/performance': typeof PerformanceIndexRoute
  '/quality': typeof QualityIndexRoute
  '/thermals': typeof ThermalsIndexRoute
  '/trips': typeof TripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/trips/$tripId': typeof TripsTripIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/engine/': typeof EngineIndexRoute
  '/fuel/': typeof FuelIndexRoute
  '/modlab/': typeof ModlabIndexRoute
  '/performance/': typeof PerformanceIndexRoute
  '/quality/': typeof QualityIndexRoute
  '/thermals/': typeof ThermalsIndexRoute
  '/trips/': typeof TripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/trips/$tripId'
    | '/dashboard/'
    | '/driver/'
    | '/engine/'
    | '/fuel/'
    | '/modlab/'
    | '/performance/'
    | '/quality/'
    | '/thermals/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/trips/$tripId'
    | '/dashboard'
    | '/driver'
    | '/engine'
    | '/fuel'
    | '/modlab'
    | '/performance'
    | '/quality'
    | '/thermals'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/trips/$tripId'
    | '/dashboard/'
    | '/driver/'
    | '/engine/'
    | '/fuel/'
    | '/modlab/'
    | '/performance/'
    | '/quality/'
    | '/thermals/'
    | '/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  TripsTripIdRoute: typeof TripsTripIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  EngineIndexRoute: typeof EngineIndexRoute
  FuelIndexRoute: typeof FuelIndexRoute
  ModlabIndexRoute: typeof ModlabIndexRoute
  PerformanceIndexRoute: typeof PerformanceIndexRoute
  QualityIndexRoute: typeof QualityIndexRoute
  ThermalsIndexRoute: typeof ThermalsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine/': {
      id: '/engine/'
      path: '/engine'
      fullPath: '/engine/'
      preLoaderRoute: typeof EngineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel/': {
      id: '/fuel/'
      path: '/fuel'
      fullPath: '/fuel/'
      preLoaderRoute: typeof FuelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modlab/': {
      id: '/modlab/'
      path: '/modlab'
      fullPath: '/modlab/'
      preLoaderRoute: typeof ModlabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance/': {
      id: '/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof PerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/': {
      id: '/quality/'
      path: '/quality'
      fullPath: '/quality/'
      preLoaderRoute: typeof QualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thermals/': {
      id: '/thermals/'
      path: '/thermals'
      fullPath: '/thermals/'
      preLoaderRoute: typeof ThermalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  TripsTripIdRoute: TripsTripIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  EngineIndexRoute: EngineIndexRoute,
  FuelIndexRoute: FuelIndexRoute,
  ModlabIndexRoute: ModlabIndexRoute,
  PerformanceIndexRoute: PerformanceIndexRoute,
  QualityIndexRoute: QualityIndexRoute,
  ThermalsIndexRoute: ThermalsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
