/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router's Vite plugin.
// It will be overwritten on the first `bun run dev-web` or `bun run dev`.
// Do NOT edit this file manually.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

import { Route as rootImport }              from './routes/__root'
import { Route as IndexImport }             from './routes/index'
import { Route as AuthLoginImport }         from './routes/auth/login'
import { Route as AuthCallbackImport }      from './routes/auth/callback'
import { Route as DashboardIndexImport }    from './routes/dashboard/index'
import { Route as TripsIndexImport }        from './routes/trips/index'
import { Route as TripsTripIdImport }       from './routes/trips/$tripId'

const IndexRoute            = IndexImport.update({ path: '/', getParentRoute: () => rootImport } as never)
const AuthLoginRoute        = AuthLoginImport.update({ path: '/auth/login', getParentRoute: () => rootImport } as never)
const AuthCallbackRoute     = AuthCallbackImport.update({ path: '/auth/callback', getParentRoute: () => rootImport } as never)
const DashboardIndexRoute   = DashboardIndexImport.update({ path: '/dashboard/', getParentRoute: () => rootImport } as never)
const TripsIndexRoute       = TripsIndexImport.update({ path: '/trips/', getParentRoute: () => rootImport } as never)
const TripsTripIdRoute      = TripsTripIdImport.update({ path: '/trips/$tripId', getParentRoute: () => rootImport } as never)

export const routeTree = rootImport.addChildren([
  IndexRoute,
  AuthLoginRoute,
  AuthCallbackRoute,
  DashboardIndexRoute,
  TripsIndexRoute,
  TripsTripIdRoute,
])

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootImport }
    '/auth/login': { id: '/auth/login'; path: '/auth/login'; fullPath: '/auth/login'; preLoaderRoute: typeof AuthLoginImport; parentRoute: typeof rootImport }
    '/auth/callback': { id: '/auth/callback'; path: '/auth/callback'; fullPath: '/auth/callback'; preLoaderRoute: typeof AuthCallbackImport; parentRoute: typeof rootImport }
    '/dashboard/': { id: '/dashboard/'; path: '/dashboard'; fullPath: '/dashboard/'; preLoaderRoute: typeof DashboardIndexImport; parentRoute: typeof rootImport }
    '/trips/': { id: '/trips/'; path: '/trips'; fullPath: '/trips/'; preLoaderRoute: typeof TripsIndexImport; parentRoute: typeof rootImport }
    '/trips/$tripId': { id: '/trips/$tripId'; path: '/trips/$tripId'; fullPath: '/trips/$tripId'; preLoaderRoute: typeof TripsTripIdImport; parentRoute: typeof rootImport }
  }
}
